# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-05 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortenedurl',
            old_name='shortened',
            new_name='shortened_url',
        ),
    ]
