# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-06-06 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0002_auto_20170605_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='shortened_url',
            field=models.CharField(db_index=True, max_length=6),
        ),
    ]
